#define LINUX 1
#define WINDOWS 0
#define APPLE 0
#define MSVC 0
#define MINGW 0
#define CMAKE_MAKE_PROGRAM /usr/bin/make
#define CMAKE_SYSTEM_NAME Linux
#define CMAKE_HOST_SYSTEM_NAME Linux //Windows, Linux or Darwin (OS X)
#define CMAKE_HOST_SYSTEM_PROCESSOR x86_64
#define CMAKE_CXX_COMPILER_VERSION 9.1.0
#define TILESON_PROJECT_VERSION_MAJOR 0
#define TILESON_PROJECT_VERSION_MINOR 1
#define TILESON_PROJECT_VERSION_PATCH 0
